services:
  db:
    image: mysql:8.4
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - youth-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: spring_backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      python:
        condition: service_started
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${JDBC_URL}
      SPRING_DATASOURCE_USERNAME: ${JDBC_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${JDBC_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    expose:
      - "8080:8080"
    networks:
      - youth-network
#
#  nginx:
#    image: nginx:latest
#    restart: "unless-stopped"
#    container_name: nginx
#    ports:
#      - "80:80"
#      - "443:443"
#    depends_on:
#      - app
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d
#      - ./frontend/dist:/usr/share/nginx/html
#    networks:
#      - youth-network\

  python:
    build: ../python-api
    container_name: python-api
    env_file:
      - .env
    restart: unless-stopped
    expose:
      - "8001:8001"
    networks:
      - youth-network


networks:
  youth-network:
    driver: bridge

volumes:
  mysql_data: