services:
  db:
    image: mysql:8.4
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - youth-network

  app:
    build: .
    container_name: spring_backend
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${JDBC_URL}
      SPRING_DATASOURCE_USERNAME: ${JDBC_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${JDBC_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - youth-network


networks:
  youth-network:
    driver: bridge
volumes:
  mysql_data: